apiVersion: v1
kind: ServiceAccount
metadata:
  name: churn-sa
  namespace: churn-model
  annotations:
    azure.workload.identity/client-id: "519d4b2c-f7ad-4009-9f13-2db6ca5b236b"
  labels:
    azure.workload.identity/use: "true"
